---
# tasks file for cve_2024_3094

- name: Run xz --version
  ansible.builtin.command:
    cmd: xz --version
  register: xz_version
  failed_when:
    - xz_version.stdout | ansible.builtin.regex_search("5\.6\.(0|1)")

- name: Find sshd path
  ansible.builtin.find:
    paths:
      - /usr/bin
      - /usr/sbin
      - /usr/local/bin
      - /usr/local/sbin
    patterns: sshd
  register: sshd_path
  failed_when: false
  changed_when: false

- name: Inspect sshd when installed
  when:
    - sshd_path.files | length > 0
  block:
    - name: Install requirements
      ansible.builtin.package:
        name: "{{ cve_2024_3094_requirements }}"

    - name: Check for f30f1e... in hexdump output
      ansible.builtin.command:
        cmd: hexdump -ve '1/1 "%.2x"' {{ sshd_path.files[0].path }}
      register: hexdump_output
      changed_when: false
      failed_when:
        - hexdump_output.stdout | ansible.builtin.regex_search("f30f1efa554889f54c89ce5389fb81e7000000804883ec28488954241848894c2410")
